# Generated by Django 5.0.7 on 2024-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.CharField(default='100/-', max_length=5),
        ),
    ]
